### ISSUE TITLE
can not index all files in current work directory

### ISSUE THREAD

**Issue by allenzt** [Yggdroot/LeaderF#119]
LeaderF can not index all files in current work directory when I trigger it by <leader>F . In my case, I can not find Makefile in qca-ssdk and qca-ssdk-shell.
test steps:
enter into shortcut-fe and launch vim, then type <leader>F, input Makefile .
PC enviroment:
ubuntu 16.04,  vim 8.0 patch 1-1458
attachment: [shortcut-fe.tar.gz](https://github.com/Yggdroot/LeaderF/files/1800047/shortcut-fe.tar.gz)

Thanks for your effort!

**Comment by Yggdroot** [comment]
This is because there are 2 repositories in your project. The `ssdk` directory is a separate reposigory. So if you use `git ls-files` in `shortcut-fe`, the files in `ssdk` can not be listed.

You can set `let g:Lf_UseVersionControlTool = 0` in your vimrc, so that LeaderF uses `rg` or `ag` or `pt` or `find` to list the files.

**Comment by allenzt** [comment]
It works, thanks for your help!
