### ISSUE TITLE
how to add the file list to args , then i can use argdo to replace the words .

### ISSUE THREAD

**Issue by irreallich** [Yggdroot/LeaderF#333]
- vim or neovim? 
    - [ yes] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [yes ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
I use rg “ leaderf！ rg -e xxxxxx ” to search something, it is ok, then i got a list as "grep -nr"
how to add the filelist to args , then i can use argdo to replace the words .
thanks.

**Comment by Yggdroot** [comment]
Currently, there is no such a feature.

In my opinion, if you want to replace the words, you don't have to  use `leaderf！ rg -e xxxxxx`  beforehand.

**Comment by irreallich** [comment]
thanks and close this issue

**Comment by xaljer** [comment]
@Yggdroot , In my opinion, `Leaderf rg` and `Leaderf gtags` are good ways to narrow down the range of replace. In very huge code repo, I think using replace of vim in million files would be quite slow and unpredictable (you don't know which files would be changed). Since rg and gtags are fast enough and I already optimize them in my work flow (such as select file type or search in part of path), they should be useful to preview what will be changed and further more to delete files you don't want to be replaced. And then, give the results to replace function to do faster and safer operations.
Since rename function of LSP  not always works fine, replace function based on search and tags is important.
I did search the work flow of replacing in multi files in vim on internet. I found that a classify method is that search first by vimgrep, than do replace by `cdo %s/<search term>/<replace term>/cg`. Since `Leaderf rg` is aim to provide a better vimgrep, the original work flow of vimgrep&cdo should be inherited.

https://jdhao.github.io/2020/03/14/nvim_search_replace_multiple_file/

**Comment by Yggdroot** [comment]
Currently, there is a workaround.
If you are using `Leaderf rg`, press `Q` in normal mode, the result will be imported into quickfix window, then `cdo xxx`.

In the future, I'll consider to add replacement feature for `Leaderf rg`.

**Comment by xaljer** [comment]
That's cool. I think current method is pretty well by co-work between different tools. It would be better if `Leaderf gtags` can support it too.

**Comment by xaljer** [comment]
I found a tool looks pretty cool to do replace work: https://github.com/ms-jpq/sad

**Comment by Yggdroot** [comment]
I add a replacement feature for `Leaderf rg`, which can be used for refactoring. 
usage:
In normal mode, add the following commands:
**r** : replace a pattern
**w** : apply the changes to buffer without saving
**W** : apply the changes to buffer and save
**U** : undo the last changes applied

If the buffer has been changed, `:w` and `:W` are the same as `w` and `W` in normal mode.
Command `:Undo` is the same as `U` in normal mode.

PS: popup mode in vim does not support this feature.
