### ISSUE TITLE
Use current NVim/Vim colorscheme as default

### ISSUE THREAD

**Issue by dkvasnicka** [Yggdroot/LeaderF#419]
I appreciate the ability to set a separate colorscheme for LeaderF (and it's popup version) but I don't understand why it is using a custom color scheme without regard to what the user is currently using, by default.

Could you please use the current Vim color scheme by default to render all your visuals and if not, could you at least add a config option to enable that?

I've switched to `gruvbox_material` which made things a little better but it feels really weird to have to spend time on playing with `g:Lf_PopupPalette` to get a consistent look.

Other than that this plugin rocks and is replacing `fzf.vim` fast in my setup!

**Comment by dkvasnicka** [comment]
Sorry, I just realized the popup takes just regular Vim colorschemes and using mine works.

**Comment by dkvasnicka** [comment]
It does not really work the way it should. Using the default colorscheme works but then the popup blends with the surroundings. It would be nice to have a popup that is _themed_ using the _palette_ from the current colorscheme but uses the colors in a way that it's clearly separated from the underlying UI.

When I copy a regular Vim colorscheme to `~/.vim/plugged/LeaderF/autoload/leaderf/colorscheme/popup` and use it, opening LeaderF "infects" the whole NeoVim with that scheme.

**Comment by Yggdroot** [comment]
The reason is that popup/floating window use `Pmenu` as the default color, for many colorschemes, this color does not look good.

> When I copy a regular Vim colorscheme to ~/.vim/plugged/LeaderF/autoload/leaderf/colorscheme/popup

This is not the place to put vim colorscheme,  it is the place to put LeaderF's popup window colorscheme.  As you can see in https://github.com/Yggdroot/LeaderF/blob/master/autoload/leaderf/colorscheme/popup/default.vim.

https://github.com/Yggdroot/LeaderF/blob/095d84dab0145979489aed80b061522eed66f023/autoload/leaderf/colorscheme/popup/default.vim#L16-L24

You can change the colors of `Lf_hl_popup_inputText`, `Lf_hl_popup_window` and `Lf_hl_popup_blank`  to get a consistent look.
For example,
```vim
hi def link Lf_hl_popup_inputText StatusLine
hi def link Lf_hl_popup_window Pmenu
hi def link Lf_hl_popup_blank StatusLine
```
