### ISSUE TITLE
when I got a search result as learderfFile and press  enter .I got error message

### ISSUE THREAD

**Issue by laihuchun** [Yggdroot/LeaderF#612]
I use python2.7.6.
error('Vim(drop):E319: Sorry, the command is not available in this version: keepj hide drop ~/test.md',)
![image](https://user-images.githubusercontent.com/3411002/83616299-3e8ab800-a5ba-11ea-9d82-8e8d8845fe40.png)
![image](https://user-images.githubusercontent.com/3411002/83616092-ff5c6700-a5b9-11ea-8114-3673f0b89cc0.png)

**Comment by Yggdroot** [comment]
vim or neovim?

- [ ] vim

- [ ] neovim

Output of vim --version or nvim --version:

**Comment by Yggdroot** [comment]
You should use 8.0.1508+, otherwise, `let g:Lf_JumpToExistingWindow = 0`.

**Comment by laihuchun** [comment]
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 22 2019 19:03:04)
Garbage after option argument: "-version"

**Comment by laihuchun** [comment]
> You should use 8.0.1508+, otherwise, `let g:Lf_JumpToExistingWindow = 0`.

It worked .tks

**Comment by serpent7776** [comment]
I'd suggest adding an entry to FAQ saying that is case of `:drop` not being available, one should `let g:Lf_JumpToExistingWindow = 0`.
The title of this issue could also be changed to something more meaningful like "drop command is not available in this version" so that other people can more easily find it.
