### ISSUE TITLE
Feature Request: support '--trim' option in Leaderf rg

### ISSUE THREAD

**Issue by xaljer** [Yggdroot/LeaderF#763]
By the way, why Leaderf need to support every option of rg respectively but not just give the option to rg? Or add kind of black list for option which need special process.

**Comment by Yggdroot** [comment]
You can add any option of rg to g:Lf_RgConfig.

Because some options may break the functionality of LeaderF, for example, '--trim' option will make the replacement in `Leaderf rg`  work incorrectly.

**Comment by xaljer** [comment]
Thanks for answer.
By the way, about the g:Lf_RgConfig, Rg also support config file specified by environment variable, can I use that way in Leaderf?
Because some of configuration may be environment relative, and I want to only put environment independent configs in the vimrc.

**Comment by Yggdroot** [comment]
I'm not sure. I think it should work.

**Comment by xaljer** [comment]
It didn't work, can rg run from Leaderf get the environment variable export in my bash ?

**Comment by Yggdroot** [comment]
Can you give me an example that how you use it?

**Comment by Yggdroot** [comment]
Oh, yeah, `--no-config` is added by default in order not to read configurations from user. Because this can prevent unexpected behavior.
Before, user opened the issue to ask why `Leaderf rg` does not work well, it turn out to be that rg has read the configurations from ripgreprc.

https://github.com/Yggdroot/LeaderF/blob/25219bf85dcbc1c497d06a85ca9684b130536a31/autoload/leaderf/python/leaderf/rgExpl.py#L303-L305

**Comment by xaljer** [comment]
oh, I see. May be those options can be more detailed in documentation, since Leaderf can use rg like in the shell, but indeed there are some limitation on it.

**Comment by Yggdroot** [comment]
Yes, e.g. `-I, --no-filename`.
rg in the cmdline just print the output, but `Leaderf rg` needs to use the output for secondary fuzzy filter and jump to the right place of the target file in vim.
